<a href="https://colab.research.google.com/github/ShreyanshiJaiswal/Python_Learning_log/blob/main/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Importing the library for Numpy.

In [ ]:
a = [1,2,3,4]
a_array = np.array(a)
a_array

array([1, 2, 3, 4])

So, we have created an array in numpy here. As we can see that it looks like a list in python but it's not. Through the next code block we will get to know about it that how it's different.

In [ ]:
a_array.dtype

dtype('int64')

Here, we have checked the data type of the array which says it's integer.

In [ ]:
a = [1,2.0,3,4]
a_array = np.array(a)
a_array.dtype

dtype('float64')

So, what we did here we just chnaged the value from 2 to 2.0 and then checked the datatype of the array that we created. It can clearly be seen here that now an array can take only one data type. The moment we change the value of 2 rest of the other parameters in our array is considered as a float regradless of the fact that we have not made any changes in it. In the above code we can see the changes happened in the array datatype

**This is the major difference between an array and in the list.
List - It can hold elements of different datatype. We can have int, boolean , float, string.
Array - So an array in numpy can hold only one type of data element.**

In [ ]:
a_array.ndim

1

This tells us about the dimension of the array in numpy.

In [ ]:
a = [[1,2,3],[4,5,6]]
a_array = np.array(a)
a_array

array([[1, 2, 3],
       [4, 5, 6]])

So this is a two dimensional array as we can see it looks quite like a matrix so the first row starts at 0 and goes on similarly the first column starts at 0 and goes on. It is also called list of lists.

In [ ]:
a_array.ndim

2

As we can see ndim is showing that it is a 2 dimensional array.

In [ ]:
a_array.size

6

This tells us the number of values we have in our matrix.

In [ ]:
a_array.shape

(2, 3)

So, this is basically telling us the number of rows and columns we have in our matrix. (row, columns). In our array it is 2 rows and 3 columns.

**List vs NumPy Array:
A Python list is like a mixed shopping bag — flexible but scattered in memory and slower to process. A NumPy array is like a neat box of only numbers, stored side by side in memory, making it compact and much faster. For example, doubling 10 lakh numbers with a list takes time, but with a NumPy array it happens almost instantly because it works on the whole block at once.**

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array.size
a_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

here it is a 3x3 matrix but it is still a two dimensional array. It can be seen below.

In [ ]:
a_array.shape

(3, 3)

In [ ]:
a_array.ndim

2

In [ ]:
#access elements in array
#a_array[row,column]
a_array[2,2]

np.int64(9)

Above here we tried to access the values in the array by using their index values and also as it was discussed earlier that the row number starts from 0 and goes on and so does the column , so basically its the index value . Here we can do negative slicing and rest of the other things as well.

In [ ]:
a_array[2,-1]

np.int64(9)

In [ ]:
a_array[2,:]

array([7, 8, 9])

In [ ]:
a_array[:,1]

array([2, 5, 8])

In [ ]:
a_array[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
#assign a value/change a value
a_array[2,2]=11
a_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 11]])

In [ ]:
a_array[0:2,1:3]=[[9,10],[8,6]]
a_array

array([[ 1,  9, 10],
       [ 4,  8,  6],
       [ 7,  8, 11]])

**Creating 3 dimensional array**

In [ ]:
a = [[[1,2],[3,4]],[[5,6],[7,8]]]
a_array = np.array(a)
a_array.ndim

3

called as lists within list

In [ ]:
a_array.shape

(2, 2, 2)

In [ ]:
a_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Important thing to notice here is that the part [[1, 2],[3, 4]] is the first elememt of the matrix similarly, this is [[5, 6],[7, 8]] the second element in the matrix. But the counting for it starts from 0 and goes on. It is explained below in the code

In [ ]:
#accessing values from a 3 dimensional array
#a_array[element,row,column]
a_array[0,0,0]

np.int64(1)

Here 0th element means we are taking the first element of the matrix and from that element we take the first row and the first column.

In [ ]:
a_array[1,1,0]

np.int64(7)

**Creating Numpy Array without creating a list**

In [ ]:
#initialiaze arrays
a_array=np.zeros(5)
a_array

array([0., 0., 0., 0., 0.])

By default it takes decimal values in arrays. But we can convert it as well.

In [ ]:
a_array=np.zeros(5,dtype='int64')
a_array

array([0, 0, 0, 0, 0])

here we have passed the desired datatype as integer.Thus we are getting integers.

In [ ]:
a_array=np.zeros((2,3),dtype='int32')
a_array

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

here we have told the numpy to create a matrix where we want 2 rows and three columns and the datatype should be integer

In [ ]:
a_array=np.ones((2,3),dtype='int32')
a_array

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

Like previously we have written np.zeros so the actual values in the matrix were zero and now in the above code we have replaced it by 1.

In [ ]:
a_array=np.full((2,3),99)
a_array

array([[99, 99, 99],
       [99, 99, 99]])

Here we have passed the function np.full and then passed the matrix size and the exact values that we want. The exact values can be anything from 0 to n.

In [ ]:
#array of random decimal values
a_array=np.random.rand(2,3)
a_array

array([[0.36765286, 0.51616536, 0.75159027],
       [0.68075956, 0.70979544, 0.40162225]])

It has created a random array of a random decimal number.

In [ ]:
#array of identity matrix
a_array=np.identity(5)
a_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

So this is an identity matrix we just have to pass the number and the numpy will create an nxn matrix and diagonally we will have 1 as a value and the rest will be all zero. Since it is an identity matrix.

**Mathematics**

In [ ]:
a_array=np.identity(3,dtype='int32')
a_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [ ]:
a_array=a_array+2
a_array

array([[7, 6, 6],
       [6, 7, 6],
       [6, 6, 7]], dtype=int32)

Basically what it did here is it added the 2 in every value we have in our matrix. But here since i run the code three times it is diagonally-1(after 3 times it became-1--->3---->5---->7) similary for the rest as well.

In [ ]:
a_array=a_array*2
a_array

array([[14, 12, 12],
       [12, 14, 12],
       [12, 12, 14]], dtype=int32)

Here we have multiplied it by 2. SImilarly we can perform division, subtraction as well.

In [ ]:
a_array1=np.full((3,2),9,dtype='int32')
a_array2=np.full((3,2),5,dtype='int32')
print(a_array1)
print(a_array2)

[[9 9]
 [9 9]
 [9 9]]
[[5 5]
 [5 5]
 [5 5]]


So here we have created a 3x2 matrix, 2 arrays to perform addition. Like we can also add matrices.

In [ ]:
a_array1=np.full((2,3),9,dtype='int32')
a_array2=np.full((2,3),5,dtype='int32')
print(a_array1)
print(a_array2)
a_array1+a_array2

[[9 9 9]
 [9 9 9]]
[[5 5 5]
 [5 5 5]]


array([[14, 14, 14],
       [14, 14, 14]], dtype=int32)

We just added the 2 matrix. One thing to keep in mind while doing so is that the dimension should be same like no. of rows and columns for both should be same.

Similarly we can perform multiplication,subtraction,trignomo,etry, division etc.

In [ ]:
a_array1=np.full((2,3),9,dtype='int32')
a_array2=np.full((2,3),5,dtype='int32')
print(a_array1)
print(a_array2)
a_array1*a_array2

[[9 9 9]
 [9 9 9]]
[[5 5 5]
 [5 5 5]]


array([[45, 45, 45],
       [45, 45, 45]], dtype=int32)

In [ ]:
a_array=np.identity(3,dtype='int32')
a_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [ ]:
 #trigonometry
np.sin(a_array)

array([[0.84147098, 0.        , 0.        ],
       [0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.84147098]])

It is giving the sin of every value we have in our a_array

In [ ]:
#statistics
a = [[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.min(a_array)

np.int64(1)

In [ ]:
np.max(a_array)

np.int64(9)

In [ ]:
np.mean(a_array)

np.float64(5.0)

In [ ]:
np.min(a_array,axis=0)

array([1, 2, 3])

here axis 0 means it checking column wise minimum value.

In [ ]:
np.min(a_array,axis=1)

array([1, 4, 7])

here axis 1 means it is checking minimun value in row wise.

Similarly we can do sum, subtraction etc.

In [ ]:
np.sum(a_array,axis=1)

array([ 6, 15, 24])

It is row wise summing all values.

In [ ]:
#re arrange
a = [[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

here we have re arranged the matrix we changed the rows to 1 and columns to 9.

In [ ]:
# merging rows
a_array1=np.full((2,3),9,dtype='int32')
a_array2=np.full((2,3),5,dtype='int32')
print(a_array1)
print(a_array2)
a_array1+a_array2

[[9 9 9]
 [9 9 9]]
[[5 5 5]
 [5 5 5]]


array([[14, 14, 14],
       [14, 14, 14]], dtype=int32)

In [ ]:
np.vstack((a_array1,a_array2))

array([[9, 9, 9],
       [9, 9, 9],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

we have vertically stacked the matrix.

In [ ]:
np.hstack((a_array1,a_array2))

array([[9, 9, 9, 5, 5, 5],
       [9, 9, 9, 5, 5, 5]], dtype=int32)

Here it has horizontally stacked the matrix.

In [ ]:
# Create a dummy file for demonstration
with open('readnp.txt', 'w') as f:
    f.write('1,2,3\n4,5,6\n7,8,9')

In [ ]:
#create array from a file
f=np.genfromtxt('readnp.txt',dtype='int32',delimiter=',')
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

here we have extracted the data from the file.

In [ ]:
#advanve indexing
f<8

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

Here we are checking which values are less than 8. where is it les it returns true else false.

In [ ]:
f<8
f[f<8]

array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

here we put the condition to only return values where there is true.

In [ ]:
#advanve indexing
#f<8
#f[f<8]
f[(f>5) & (f<10)]

array([6, 7, 8, 9], dtype=int32)

we have put another condition check that values should be greater than 5 but less than 8.

In [ ]:
f[(f>5) | (f<10)]

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

SO here we performed the or condition.